### ISSUE TITLE
Allow to provide schema

### ISSUE THREAD

**Issue by tunger** [OctopusDeploy/Nevermore#101]
It would be great to be able to specify the schema for tables/objects. Right now, the "dbo." identifier is hardcoded. 

I saw that there is already a [SchemaName](https://github.com/OctopusDeploy/Nevermore/blob/49b67f82b3aaac38f47fdd564fa86356d4f5665d/source/Nevermore/Mapping/DocumentMap.cs#L22) property in the DocumentMap, however setting it has no effect as it's not (yet) used.

Is this planned, or do you want a contribution / PR?

I'm eager to test this library out in a small application.
Thanks!

**Comment by PaulStovell** [comment]
Funny - I added it with the intention of making it work, but haven't got around to it. Happy to accept a PR :)
