### ISSUE TITLE
Improve docs: Related Documents

### ISSUE THREAD

**Issue by tunger** [OctopusDeploy/Nevermore#115]
I saw in source and in tests that one can use Related Doucments mapping. However, I can't quite figure out how (or when) to best use them. It looks like there needs to be a table in a certain format to use them.

It would be great to have a page in wiki that explains this feature, its configuration, and queries how to best load joined/related documents.

**Comment by PaulStovell** [comment]
I don't actually believe related documents is a Nevermore concern (it could be handled in Hooks). Right now keeping them there is a pragmatic solution since Octopus relies on them, but I haven't documented it because I don't believe it's the best solution.
