### ISSUE TITLE
Badly formatted directory string error from Nevermore v2 (null handling)

### ISSUE THREAD

**Issue by MarkSiedle** [OctopusDeploy/Nevermore#119]
An issue came up during [QRF](https://trello.com/c/DZT902DA/3488-help-ziaul-with-variables-exception-certificates-all-exception) regarding blank subjects in certificate names - see [Octopus Server PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/6431).

This was traced back to changes in Nevermore v2 conversion. Ideally we should not need this null-wrapping check in the Octopus Server.

Would it be possible to handle this in Nevermore instead?

**Comment by MarkSiedle** [comment]
cc @slewis74 @alialmaktoum - will leave this in your very capable hands please.

**Comment by PaulStovell** [comment]
I don't think there's anything Nevermore can do about this - Nevermore exposes the data reader's raw API here (for the custom type handler) so it's up to the user to check for IsDBNull but also for empty strings. It would seem incorrect for IsDBNull to also return true if it's empty for example.
