### ISSUE TITLE
Actively maintained?

### ISSUE THREAD

**Issue by tunger** [OctopusDeploy/Nevermore#120]
Hello,

First of all, after a trial run of using Nevermore in a small project I'm really fond of the idea behind it and how easy it is to work with.

This is not meant as a critique, but I would like to ask what the plans for this project / open repo are. I noticed that there are no reactions to PRs or issues I opened a month ago. This does not motivate me to invest further time into improving it.

Will Nevermore remain the ORM solely for Octopus Deploy, with little community focus?
If so, I will probably switch to Marten. Even if it's a bit complicated in my company to get a PostgreSQL instance.

Thanks

**Comment by PaulStovell** [comment]
Hi Thomas, sorry your PR's languished for so long - I just merged two of them and am going to take a deeper look at the ID types one before merging it. 

I'd like Nevermore to be more of a community project and not Octopus specific. I have a real interest in Nevermore and it keeps me connected to coding. Missing the PR's wasn't a matter of not wanting community contributions - just a matter of not checking the notifications.

**Comment by tunger** [comment]
Alright, thanks for clarification, good to know!
