### ISSUE TITLE
Compression: migration

### ISSUE THREAD

**Issue by PaulStovell** [OctopusDeploy/Nevermore#98]
Nevermore 2.0 is getting the ability to compress documents. In testing locally, this can have a huge impact on the performance of Octopus when the database is not on the same server as Octopus:

https://github.com/OctopusDeploy/Nevermore/wiki/Compression

The one downside is that it comes with a hefty migration cost: needing to load (in C#) every document and re-save it. 

Potential solutions:

**Stop the world, big bang**: 

We write a C# data migration that runs when customers upgrade. You can imagine that this could take some time - especially when processing thousands of records. This seems like a bad customer experience.

**Side-by-side and background processing**

We add a new column to the table called `[JSONBlob]`, and make Nevermore able to read and write both columns side-by-side (if compression is enabled, preferring to read from `JSONBlob`). 

We can then run a background task that slowly churns through every document, converting the JSON from one format to another. Eventually, the old column could be dropped when there are no more rows with that value. 

This would make the upgrade for customers faster, though it will probably then take longer for the migration to finish. 

What other solutions would work here?

Are we happy with the name `[JSONBlob]` for gzipped JSON? 

Rules/logic:

 - `[JSON]` is always text (`nvarchar(max)`). 
 - `[JSONBlob]` is always JSON text that is UTF-8 encoded, GZipped `varbinary(max)`
 - Tables can have both columns, but one will typically have null values
 - When `Compressed` is enabled on the `DocumentMap`:
    - Nevermore will read from `[JSONBlob]` first, falling back to `[JSON]` if it's empty
    - Nevermore will write to `[JSONBlob]`, and null `[JSON]` when it does
 - When `Compressed` is disabled on the `DocumentMap`:
    - Nevermore will read from `[JSON]` first, falling back to `[JSONBlob]` if it's empty
    - Nevermore will write to `[JSON]`, and null `[JSONBlob]` when it does

The background migrator will:

 - Load a batch of documents from a table by selecting the JSON column as text
 - Convert it to the binary format
 - Update it back

**Comment by droyad** [comment]
My initial reaction was we would lose the ability to use `json_value`, but I assume you can do `json_value(DECOMPRESS(Json), '$.foo'`?

How does this affect CPU usage? If say multiple threads are fetching from the `Machine` table that has 1000's of rows? It's like not as much of an issue now with the FullTableCache, but I do remember the deserialization time on the server was significant.

Octopus `2020.2` will [have the right minimum requirements](https://octopusdeploy.slack.com/archives/CDANN5QLT/p1586911709142700)

**Comment by droyad** [comment]
We would lose the ability to add indexes to the JSON column

**Comment by PaulStovell** [comment]
> My initial reaction was we would lose the ability to use json_value, but I assume you can do json_value(DECOMPRESS(Json), '$.foo'?

Not quite unfortunately. 

After `DECOMPRESS`, you need to cast it to a string type. But what type do you use? The text will be UTF-8 encoded, but only SQL 2019 understands what UTF-8 is. `varchar` doesn't work because it's ASCII, and `nvarchar` doesn't work because it's UCS-2 (or UTF-16 depending on code). 

The only solution would be something like:

````
json_value(Utf8ToText(DECOMPRESS([JSONBlob])), '$.foo')
```

Where Utf8ToText is a user-defined function.

The only alternative is if we write the data as UCS-2. That takes twice the bytes and might still fail if the user has the wrong collation. Do we enforce a collation in the Octopus database?

**Comment by PaulStovell** [comment]
Re: CPU usage - for small/midsize documents it seems roughly the same (at least on my PC) (fewer bytes to read/GC, more work decompressing it).

**Comment by droyad** [comment]
I just ran
```
ALTER TABLE VariableSet ADD JSONBlob varbinary(max) NULL
GO
UPDATE VariableSet SET JSONBlob = COMPRESS(Json)
```
 on a table with 1GB of JSON and 64,000 rows (`VariableSet`). It completed in 78 seconds and compressed size was 280MB.

The events table, 3.2GB, 1,700,000 rows took 10 minutes

**Comment by PaulStovell** [comment]
OK, changed the encoding (not UTF8 anymore) and we can now interact and query the data from SQL:

```
select count(*) from dbo.Person where JSON_VALUE(CAST(DECOMPRESS([JSON]) as nvarchar(max)), '$.Name') = N'Paul ¥ⶀＦ'
```

I will add a check (which Octopus & Nevermore can call at install or startup) that does a little round-trip like this to make sure that the collation we use in the server is compatible with the encoding we use to read/write the data. This will ensure we don't have queries that fail for certain users. 

So this lets us continue to use `JSON_VALUE` etc., we just can't index it (because of compression). In for those cases you can use a mapped column anyway.

**Comment by PaulStovell** [comment]
Update: this has been pushed, and the wiki updated on how to use it:

https://github.com/OctopusDeploy/Nevermore/wiki/Compression
